### ISSUE TITLE
New bios

### ISSUE THREAD

**Issue by verge27** [cloudnull/mining-gpu-vbios#1]
Hey

Flashed with the HV rom and it stepped the GPU hash to 25.25 on ETH on Ethos.
Flashed with the basal rom and its stepped up slightly from your previous revision to 27.15-25.

Thank you - will buy you a beer when nanopool pays out!

**Comment by verge27** [comment]
Pushed the memory clocks to 2250  and getting 27.35Mh/s peak, stable 27.21 - 27.27.
Memstate of 2230 was downclocking slightly in Ethos.

**Comment by cloudnull** [comment]
Nice! I will make the memory revision ASAP pushing things to 2250 stock.

**Comment by verge27** [comment]
You are doing well man - keep it up. You are leading the way on the bios revision for this card/mem for ETH mining.

**Comment by cloudnull** [comment]
Sorry for the late reply, I ran into some stability issues when I made the last updates.  I've spent a couple days testing and have ironed out the issues and committed the changes here: https://github.com/cloudnull/mining-gpu-vbios/commit/879c6cc687c3405cafc428d3700aa75362b10a6f

Note that I encountered two different hardward revisions and adjusted accordingly.

**Comment by verge27** [comment]
Cool thanks - will test them out. Still waiting for Nanopool to pay out :)

**Comment by verge27** [comment]
No different for me between revisions on outset -using the E revision for
no other reason than its higher order. Hash up to 27.58 - 27.64 - well done!

On 16 Feb 2018 16:01, "Steven Paterson" <st.paterson@gmail.com> wrote:

Cool thanks - will test them out. Still waiting for Nanopool to pay out :)

**Comment by cloudnull** [comment]
++ Awesome! Closing this issue for now.

**Comment by verge27** [comment]
http://98da06.ethosdistro.com

**Comment by cloudnull** [comment]
Very nice! 28 across the board and temps look great!

**Comment by cloudnull** [comment]
I'm seeing the same on my rig(s) 
![2018-02-15](https://user-images.githubusercontent.com/2066292/36320716-b4267c90-130c-11e8-9614-a219391ab5e3.png)

**Comment by verge27** [comment]
Don't have access mate? Can't seem to request.

**Comment by verge27** [comment]
At any rate - really appreciate you taking the time. Excellent work.

**Comment by verge27** [comment]
Hi

My power draw has dropped by at least 80 watts with this BIOS - that's
insane!

**Comment by cloudnull** [comment]
Thanks for the beer BTW! I really appreciate it :)

**Comment by verge27** [comment]
An absolute pleasure. Thanks again!

**Comment by verge27** [comment]
Getting a solid 28Mh/s with the new Ethos distro! - v1.3.0
